seed: 0
exp_name: exp001_train


train:
    # Please Specify Your Own Path
    CO3D_DIR: "/home/arj/code/datasets/pcd_train"
    CO3D_ANNOTATION_DIR: "/home/arj/code/datasets/pcd_train"
    
    img_size: 224
    category: seen
    restart_num: 50
    lr: 0.0001
    resume_ckpt: "/home/arj/code/datasets/pcd_train/ckpt_000000"
    # resume_ckpt: False
    epochs: 25
    ckpt_interval: 5
    num_workers: 1

    eval_interval: 1

    print_interval: 10

    len_train: 400
    len_eval: 100

    max_images: 14 # must be twice that of images_per_seq
    normalize_cameras: True
    persistent_workers: True

    pin_memory: False
    clip_grad: 1.0
    preload_image: False
    cudnnbenchmark: False
    first_camera_transform: True
    min_num_images: 7
    images_per_seq: [6,7] #does not work with DeepSpeed
    num_of_poses: 30
    compute_optical: True
    color_aug: False
    erase_aug: False
    batch_repeat: 10
    actual_batch_size: 1
debug: True

exp_dir: "/home/arj/code/datasets/pcd_train"

MODEL:
    _target_: models.PoseDiffusionModel

    pose_encoding_type: absT_quaR_logFL

    IMAGE_FEATURE_EXTRACTOR: 
        _target_: models.PointNet2_ssg_double
        # modelname: "pointnet2_ssg_cut" #n/a
        # freeze: False

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               models.TransformerEncoderWrapper
            # d_model:                512
            d_model:                256
            nhead:                  4
            # dim_feedforward:        1024
            dim_feedforward:        512
            num_encoder_layers:     8
            dropout:                0.1
            batch_first:            True
            norm_first:             True

    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
