seed: 0
exp_name: exp001_train


train:
    # Please Specify Your Own Path
    CO3D_DIR: "/home/arjay55/code/datasets/pcd_train/"
    CO3D_ANNOTATION_DIR: "/home/arjay55/code/datasets/pcd_train/"
    
    img_size: 224
    category: seen
    restart_num: 50
    lr: 0.0001
    resume_ckpt: "/home/arjay55/code/models/posediffusion_ckpt/ckpt_000049"
    epochs: 50
    ckpt_interval: 5
    num_workers: 1

    eval_interval: 5

    print_interval: 10

    len_train: 400
    len_eval: 100

    max_images: 10 # must be twice that of images_per_seq
    normalize_cameras: True
    persistent_workers: True

    pin_memory: False
    clip_grad: 1.0
    preload_image: False
    cudnnbenchmark: False
    first_camera_transform: True
    min_num_images: 2
    images_per_seq: [2,5]
    compute_optical: True
    color_aug: False
    erase_aug: False
    batch_repeat: 10

debug: False

exp_dir: "/home/arjay55/code/models/posediffusion_ckpt/"

MODEL:
    _target_: models.PoseDiffusionModel

    pose_encoding_type: absT_quaR_logFL

    IMAGE_FEATURE_EXTRACTOR: 
        _target_: models.PointNet2_ssg_cut
        # modelname: "pointnet2_ssg_cut" #n/a
        # freeze: False

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               models.TransformerEncoderWrapper
            # d_model:                512
            d_model:                256
            nhead:                  4
            # dim_feedforward:        1024
            dim_feedforward:        512
            num_encoder_layers:     8
            dropout:                0.1
            batch_first:            True
            norm_first:             True

    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
